# Created by https://github.com/EdJoPaTo/LinuxScripts/tree/master/Applications/zsh
# Heavily inspired by https://github.com/ChrisTitusTech/zsh

## enable when on Arch Linux
ZSH_PLUGINS=/usr/share/zsh/plugins

## enable when on macOS
#ZSH_PLUGINS=/usr/local/share
#fpath+=/usr/local/share/zsh-completions

# Enable colors and change prompt:
autoload -U colors && colors

# Prompt
# TODO Check theme https://github.com/romkatv/powerlevel10k
fpath+=$HOME/.zsh/pure
autoload -U promptinit; promptinit
prompt pure

# History in cache directory:
HISTSIZE=10000
SAVEHIST=$HISTSIZE
HISTFILE=~/.cache/zsh_history
# History options: https://unix.stackexchange.com/questions/273861/unlimited-history-in-zsh/273863#273863
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
#setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)               # Include hidden files.

# Load stuff
for config_file ($HOME/.zsh/*.zsh); do
    source $config_file
done

source "$ZSH_PLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" 2>/dev/null

source "$ZSH_PLUGINS/zsh-history-substring-search/zsh-history-substring-search.zsh" 2>/dev/null

#source /usr/share/nvm/init-nvm.sh

uptime
