# Created by https://github.com/EdJoPaTo/LinuxScripts/tree/master/Applications/zsh
# Heavily inspired by https://github.com/ChrisTitusTech/zsh

uptime

# Comment out your OS
#OS=archlinux
#OS=macos

if [[ "$OS" == "archlinux" ]]; then
    ZSH_PLUGINS=/usr/share/zsh/plugins
elif [[ "$OS" == "macos" ]]; then
    ZSH_PLUGINS=/usr/local/share
    fpath+=/usr/local/share/zsh-completions
else
    echo "unknown OS. Set in ~/.zshrc"
fi

# Enable colors
autoload -U colors && colors

# Prompt
# TODO Check theme https://github.com/romkatv/powerlevel10k
fpath+=$HOME/.zsh/pure
autoload -U promptinit; promptinit
prompt pure

# History
HISTSIZE=10000
SAVEHIST=8000
HISTFILE=~/.cache/zsh_history
# History options: man zshoptions
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_FIND_NO_DUPS         # Don't display duplicates of a line previously found.
setopt HIST_IGNORE_ALL_DUPS      # If a new command line being added to the history list duplicates an older one, the older command is removed  from  the  list.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt SHARE_HISTORY             # Share history between all sessions.

# Completion
autoload -U compinit
# Matching: first exact match, then uppercase from lowercase and match on the left side (bar -> foobar)
zstyle ':completion:*' matcher-list '' 'l:|=* r:|=* m:{a-z}={A-Z}'
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

# Load stuff
for config_file ($HOME/.zsh/*.zsh); do
    source $config_file
done

source "$ZSH_PLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" 2>/dev/null

source "$ZSH_PLUGINS/zsh-history-substring-search/zsh-history-substring-search.zsh" 2>/dev/null
