# Created by https://github.com/EdJoPaTo/LinuxScripts/tree/master/Applications/zsh
# Heavily inspired by https://github.com/ChrisTitusTech/zsh

# Enable colors and change prompt:
autoload -U colors && colors

# Prompt
# TODO Check theme https://github.com/romkatv/powerlevel10k
fpath+=$HOME/.zsh/pure
autoload -U promptinit; promptinit
prompt pure

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh_history
# Share history between all the sessions
setopt SHARE_HISTORY

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)               # Include hidden files.

# Load stuff
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh 2>/dev/null

#source /usr/share/nvm/init-nvm.sh

uptime
