[bell]
duration = 50
color = "#000000"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control"

[window]
blur = true
decorations = "none"
dynamic_padding = true
opacity = 0.95
