#!/usr/bin/env sh

# This file is meant to compatible with multiple shells, including: bash, fish, zsh

alias cdf='cd "$(fd --type=directory | fzf)"'
alias cdg='cd ~/git && cd "$(project-below --directory=.git --list | rg -v archived\/ | fzf)"'
alias cdga='cd ~/git && cd "$(project-below --directory=.git --list | fzf)"'

alias gitrepodir='git rev-parse --show-toplevel'
alias cdrepo='cd $(gitrepodir)'

alias brew='nice brew'
alias cargo='nice cargo'
alias code='nice -n 5 code'
alias esphome='nice esphome'
alias makepkg='nice makepkg'
alias npm='nice npm'
alias paru='nice paru'
alias pio='nice pio'
alias platformio='nice platformio'
alias podman='nice podman'
alias rustup='nice rustup'

type codium >/dev/null 2>/dev/null && alias code='nice -n 5 codium'

# Help to migrate to new commands (space at start -> no zsh history entry)
alias grep=' echo use rg && false --'
alias sudo=' echo use doas && false --'

# Add default arguments to commands (which are then always used)
alias ffmpeg='nice -n 15 ffmpeg -stats -hide_banner'
alias ffprobe='ffprobe -hide_banner'
alias ip='ip --color=auto'
alias ls='eza --git'
alias systemctl='systemctl --no-pager --full'
alias tokei='tokei --sort code'
alias yt-dlp='nice -n 15 yt-dlp --prefer-free-formats --embed-subs --sub-langs all --embed-thumbnail --embed-metadata --embed-chapters --video-multistreams --audio-multistreams --sponsorblock-remove default'

alias ffmpegGif='ffmpeg -an'
alias ffmpegSound='ffmpeg -vn'
alias randb='openssl rand -base64 33'
alias randh='openssl rand -hex 20'
alias rgf='rg --files-with-matches'
alias rsynca='rsync --verbose --checksum --delete-delay --archive'
alias rsyncc='rsync --verbose --recursive --links --copy-unsafe-links --times'
alias ssh-force-password='ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no'
alias tree='eza -al --tree --git --git-ignore'
alias yt-dlp-1440='yt-dlp --format "(bestvideo+bestaudio/best)[height<=1440]"'
alias yt-dlp-720='yt-dlp --format "(bestvideo+bestaudio/best)[height<=720]"'
alias yt-dlp-mp3='yt-dlp --extract-audio --audio-format mp3'

# https://github.com/chubin/wttr.in
alias wttr='curl wttr.in && curl v2.wttr.in'
alias wttr-short='curl "wttr.in/?format=%l:+%c+%t,+%w+%m"'

alias mpc-clearadd='mpc clear -q && mpc add'
alias mpc-cropadd='mpc crop && mpc add'
alias amp='mpc --host etoPiBedAmp'

# example usage: `gitBelow fetch`
# see: https://github.com/EdJoPaTo/project-below
alias gitBelow='project-below --directory=.git git'
alias gitSubmoduleBelow='project-below --file=.git git'

# --bind 0.0.0.0 when testing with devices on the same network
alias hugo-serve='hugo server -p 4200 --buildDrafts --buildFuture'

alias podman-image-update='nice podman pull $(podman image ls --filter=dangling=false --noheading --format="{{.Repository}}:{{.Tag}}" | rg -v localhost)'
alias podmanBelow='project-below --file=Dockerfile nice -n 19 podman'

alias cargo-open-doc='nice cargo doc --open --all-features'
alias cargo-features='cargo metadata --no-deps --format-version=1 | jq ".packages.[].features"'
alias cargoBelow='project-below --file=Cargo.toml nice -n 19 cargo'
alias cargoLibBelow='project-below --file=src/lib.rs nice -n 19 cargo'

alias npx='echo edjopato fixed npx again && PATH=$(pwd)/node_modules/.bin:$PATH nice'
alias node-test='node --enable-source-maps --test --experimental-test-coverage'
alias npm-reinstall='rm -rf node_modules package-lock.json && nice npm install --no-fund && npm outdated; npm test'
alias npm-xo-update='rm -rf node_modules package-lock.json && nice npm install --no-fund --save-dev xo@latest && nice ./node_modules/.bin/xo --fix'
alias npmBelow-ci='project-below --file=package.json nice -n 19 bash -c "rm -rf node_modules package-lock.json; git checkout package-lock.json; npm ci --no-fund 2>/dev/null || npm i --no-fund"'
alias npmBelow-clean='project-below --file=package.json --directory=node_modules rm -rf node_modules'
alias npmBelow='project-below --file=package.json nice -n 19 npm'
alias tsc-watch='rm -rf dist && nice ./node_modules/.bin/tsc --sourceMap --watch'
alias tscBelow-clean='project-below --file=tsconfig.json --directory=dist rm -rf dist'

alias denoBelow='project-below --file=deno.jsonc deno'

alias pio-upload='pio run --target upload'
alias pio-monitor='pio device monitor'
alias pioBelow='project-below --file=platformio.ini nice -n 19 pio'
alias pioBelow-clean='project-below --file=platformio.ini --directory=.pio rm -rf .pio'
