#* If the theme set background should be shown, set to False if you want terminal background transparency.
theme_background = false

#* Sets if 24-bit truecolor should be used, will convert 24-bit colors to 256 color (6x6x6 color cube) if false.
truecolor = false

#* Use a darkening gradient in the process list.
proc_gradient = false

#* If process cpu usage should be of the core it's running on or usage of the total available cpu power.
proc_per_core = true
