[theme]
theme = "native"
[icons]
icons = "awesome6"

[[block]]
block = "music"
format = " {$play $combo.str(max_width:60)|}"

[[block]]
block = "custom"
command = 'curl "https://wttr.in/?format=%m+%l:+%c%t+%w"'
interval = 600

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization $barchart"

[[block]]
block = "load"
format = " $icon $1m.eng(w:3) $5m.eng(w:3) $15m.eng(w:3)"

[[block]]
block = "memory"
format = " $icon $mem_used_percents"

[[block]]
block = "sound"
device_kind = "sink"

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %d.%b %H:%M')"

[[block]]
block = "privacy"
[[block.driver]]
name = "pipewire"
