#theme = "native"
icons = "awesome"

[[block]]
block = "music"
buttons = ["play"]
marquee = false
max_width = 60
#dynamic_width = true

[[block]]
block = "cpu"
interval = 1
#format = "{barchart} {utilization} {frequency}"
format = "{barchart}"

[[block]]
block = "load"
format = "{1m} {5m} {15m}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "net"

[[block]]
block = "sound"
device_kind = "sink"

[[block]]
block = "sound"
device_kind = "source"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
interval = 5
format = "%a %d.%m %R"
