packages = [
    "opendoas",
    "starship",
    "sudo"
]
script = """
set -eux
useradd -m edjopato
usermod -aG wheel edjopato
echo "%wheel ALL=(ALL) ALL" > /etc/sudoers.d/wheel
echo "permit :wheel" > /etc/doas.conf

chown -R edjopato:wheel /home/edjopato
"""
