packages = [
    "starship",
    "zsh-completions",
    "zsh-history-substring-search",
    "zsh-syntax-highlighting",
    "zsh"
]
shared_directories = ["LinuxScripts"]
script = """
set -eux
cd /shared_dirs/LinuxScripts/Applications/zsh
su -c - edjopato "./install.sh"
rm /home/edjopato/.config/zsh/macos-specific.zsh
"""
