packages = [
    "starship",
    "zsh-completions",
    "zsh-history-substring-search",
    "zsh-syntax-highlighting",
    "zsh"
]
script = """
set -eux
cd /home/edjopato/git/infra/LinuxScripts/configs
su -c - edjopato "./install.sh"
"""
