packages = [
    "starship",
    "zsh-completions",
    "zsh-history-substring-search",
    "zsh-syntax-highlighting",
    "zsh"
]
script = """
set -eux
cd /home/edjopato/git/personal/LinuxScripts/Applications/zsh
su -c - edjopato "./install.sh"
rm /home/edjopato/.config/zsh/macos-specific.zsh
"""
