packages = [
    "base",
    "base-devel",
    "nano",

    # some big packages so running the main script isnt as meh
    "ansible",
    "firefox",
    "gimp",
    "inkscape",
    "languagetool",
    "libreoffice-fresh",
    "podman",
    "teamspeak3",
    "telegram-desktop",
]
aur_packages = [
]
shared_directories = ["LinuxScripts"]
script = """
set -eux
cd /shared_dirs/LinuxScripts/Arch/Install

export USER=edjopato
./main.sh
"""
