[editor]
cursorline = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = false

[editor.soft-wrap]
enable = true

[editor.whitespace]
# Temporary: :set whitespace.render all
render = "none"

[editor.lsp]
display-inlay-hints = true
